### ISSUE TITLE
Issue with object

### ISSUE THREAD

**Issue by ChromuSx** [bryanmylee/svelte-previous#10]
I cannot get the library to work with an object, the previous value never appears
Could you give me a REPL example? 
Thanks in advance

**Comment by bryanmylee** [comment]
@ChromuSx Thanks for bringing this to my attention. I'm getting the same issue too, a regression must have occurred somewhere. I'll quickly fix it.

**Comment by bryanmylee** [comment]
@ChromuSx I'm still investigating the issue, and it seems to be breaking due to something intrinsic to Svelte.

You can refer to this [REPL](https://svelte.dev/repl/3e85afd6685a427085c7c9b998019f26?version=3.53.1) for some examples.

The previous object updates fine if I update the current object with `.update`, `.set`, or replace the object outright.

```ts
// All these work.
data.update(d => ({ ...d, age: d.age + 1 }));
data.set({ name: 'Bryan', age: 21 });
$data = { name: 'Bryan', age: 22 };
```

However, it breaks if I update any properties of the object through the auto-subscription syntax.

```ts
// None of these work.
$data.age++;
$data.age += 1;
$data.name = 'John';
```

I've implemented the contracts for Svelte stores correctly, so there should be no reason why the auto-subscription syntax makes a difference. I suspect there's an issue with Svelte itself.

**Comment by milcaunicorn** [comment]
#
> @ChromuSx I'm still investigating the issue, and it seems to be breaking due to something intrinsic to Svelte.
> 
> You can refer to this [REPL](https://svelte.dev/repl/3e85afd6685a427085c7c9b998019f26?version=3.53.1) for some examples.
> 
> The previous object updates fine if I update the current object with `.update`, `.set`, or replace the object outright.
> 
> ```ts
> // All these work.
> data.update(d => ({ ...d, age: d.age + 1 }));
> data.set({ name: 'Bryan', age: 21 });
> $data = { name: 'Bryan', age: 22 };
> ```
> 
> However, it breaks if I update any properties of the object through the auto-subscription syntax.
> 
> ```ts
> // None of these work.
> $data.age++;
> $data.age += 1;
> $data.name = 'John';
> ```
> 
> I've implemented the contracts for Svelte stores correctly, so there should be no reason why the auto-subscription syntax makes a difference. I suspect there's an issue with Svelte itself.


You just show svelte auto-subscriptions work exactly as they should. You have to return a updated object.

`
const age = $data.age++;
const name = $data.name
$data = { name,age}
// sorry for my const usage, use it for readability.
`
If you read the object it you can not change it.

**Comment by bryanmylee** [comment]
Thanks @milcaunicorn. Anyways, this isn't something solvable by a library like mine as it's intrinsic to the Svelte compiler.
